# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Iago Velasco | Full stack
email: iagovelasco@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programador apaixonado por linhas de código e que respira tecnologia
  Tenho 23 anos, brasileiro, graduado em Ciências da Computação,
  sou desenvolvedor Front-End e Back-End
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iagovelasco.com.br" # the base hostname & protocol for your site
enforce_ssl:      iagovelasco.com.br
twitter_username: iagovelasco1
github_username:  iagovelasco
facebok:          iago.velasco.94

fbcomments: yes

links:
  - title: Posts
    url: /posts/

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-82206807-1

# Build settings
markdown: kramdown

encoding: utf-8
lang: pt-BR
